### ISSUE TITLE
Create a VS2010 Project Template

### ISSUE THREAD

**Issue by rjhernandez** [gyurisc/BootstrapMVC#5]
This work is great, but it would be much better if it could be downloaded as a project template from the Visual Studio Extension Gallery.
Roberto.-

**Comment by gyurisc** [comment]
Hi Roberto,

I already published a project template to visual studio gallery. Although it is still not updated to 2.0. Is this what you referring to as project template?

**Comment by rjhernandez** [comment]
Yes Sir! Thanks for the update. Again great job on the original work.
